name: Deploy App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout c칩digo
        uses: actions/checkout@v3

      - name: Iniciar sesi칩n en DockerHub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Construir y etiquetar im치genes Docker
        run: |
          docker build -t miusuario/backend-go:latest ./backend-go
          docker build -t miusuario/backend-node:latest ./backend-node
          docker build -t miusuario/frontend:latest ./frontend

      - name: Subir im치genes a DockerHub
        run: |
          docker push miusuario/backend-go:latest
          docker push miusuario/backend-node:latest
          docker push miusuario/frontend:latest

      - name: Desplegar en servidor
        run: |
          ssh user@mi-servidor "docker pull miusuario/backend-go:latest && docker pull miusuario/backend-node:latest && docker pull miusuario/frontend:latest && docker-compose up -d"
